question_data = [
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "The HTML5 standard was published in 2014.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "Coca-Cola&#039;s original colour was green.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                                          "question": "The US emergency hotline is 911 because of the September 11th terrorist attacks.",
                                          "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
         "question": "The planet Mars has two moons orbiting it.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                                           "question": "The vapor produced by e-cigarettes is actually water.",
                                           "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Sports", "type": "boolean", "difficulty": "medium",
         "question": "Soccer player Cristiano Ronaldo opened a museum dedicated to himself.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Animals", "type": "boolean", "difficulty": "medium",
                                           "question": "&quot;Kamea,&quot; the Gilbertese Islander word for dog, is derived from the English phrase &quot;Come here!&quot;",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Art", "type": "boolean", "difficulty": "medium",
         "question": "Vincent van Gogh cut off one of his ears.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Geography", "type": "boolean", "difficulty": "medium",
         "question": "Gothenburg is the capital of Sweden.", "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
         "question": "In Half-Life 2, if you play the zombies&#039; speech in reverse, they actually speak coherent English.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Mythology", "type": "boolean", "difficulty": "medium",
         "question": "The Japanese god Izanagi successfully returned his wife Izanami from the Underworld.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Geography", "type": "boolean", "difficulty": "medium",
         "question": "There exists an island named &quot;Java&quot;.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Geography", "type": "boolean", "difficulty": "medium",
                                           "question": "&quot;Mongolia&quot; was a part of the now non-existent U.S.S.R.",
                                           "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
         "question": "&quot;Twenty One Pilots&quot; made the song &quot;The Motion&quot; featuring Sampha.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "The first dual-core CPU was the Intel Pentium D.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
         "question": "David Baszucki was a co-founder of ROBLOX Corporation.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Politics", "type": "boolean", "difficulty": "medium",
                                           "question": "The State of Queensland, Australia voted NO to a referendum for daylight savings in 1992.",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
         "question": "In &quot;Star Trek&quot;, Klingons are commonly referred to as &quot;Black Elves&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
         "question": "In &quot;League of Legends&quot;, there exists four different types of Dragon.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
         "question": "Sound can travel through a vacuum.", "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Cartoon & Animations", "type": "boolean", "difficulty": "medium",
         "question": "Snagglepuss was part of the Yogi Yahooies in the 1977 show Scooby&#039;s All-Star Laff-a-Lympics.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "The British organisation CAMRA stands for The Campaign for Real Ale.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                                           "question": "&quot;Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo.&quot; is a grammatically correct sentence.",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
         "question": "&quot;Tachycardia&quot; or &quot;Tachyarrhythmia&quot; refers to a resting heart-rate near or over 100 BPM.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
         "question": "The snowmobile was invented by Canadian Joseph-Armand Bombardier in 1937.",
         "correct_answer": "True",
         "incorrect_answers": ["False"]}
]
